### PR TITLE
feat: docker containerization and example docker-compose

### PR DESCRIPTION
**Pull request by JuniorJPDJ**

### CODE REVIEW

**Comment by qu1ck** [comment]
Thanks, looks good. Just move the renovate config into `.github` dir.

As far as I can tell I don't need to setup any secrets, the workflow will use github job token to publish the image on every push?

**Comment by JuniorJPDJ** [comment]
> As far as I can tell I don't need to setup any secrets, the workflow will use github job token to publish the image on every push?

for workflows? no, no need for any secrets

> Thanks, looks good. Just move the renovate config into .github dir.

This will block renovate on forks, as `/renovate.json` is default path for the config and it's being used for checking if fork should be processed.

**Comment by qu1ck** [comment]
The docs https://docs.renovatebot.com/configuration-options/#configuration-options
say nothing about forks not working if config is not in the root folder, multiple paths are searched.

**Comment by JuniorJPDJ** [comment]
https://docs.renovatebot.com/configuration-options/#forkprocessing
section `Allowed filenames`

**Comment by JuniorJPDJ** [comment]
Can you make the docker package public?

**Comment by qu1ck** [comment]
Done

**Pull request merged**
