### PR TITLE
feat(ci,Dockerfile): add caching of build directories

### PR DESCRIPTION
**Pull request by JuniorJPDJ**

### CODE REVIEW

**Review by qu1ck — COMMENTED** [review]
Given how rarely this package is built I don't think the complexity of caching is needed or will save anything. Do you have a use case for it?

**Comment by JuniorJPDJ** [comment]
I added it to all projects I did CI for. I think it's better to have it than not have it and it doesn't cost anything :D

**Comment by qu1ck** [comment]
It takes up limited cache space which may evict stuff that is more useful to my other projects.

**Comment by JuniorJPDJ** [comment]
I'm using it during builds after renovate updates some dependency, but I won't force you ;D
Take it or close it! :D

**Comment by qu1ck** [comment]
Looks like cache size is 3-15 MB which is not that significant.

**Pull request merged**
